expect_indexed <- function(x, value, unit) {
    expect_s3_class(x, "IndexedUnits")
    expect_type(x, "double")
    expect_equal(as.numeric(x), value)
    expect_equal(indexed_unit_labels(x), unit)
    expect_length(attr(x, "unit_id"), length(x))
}

test_that("indexed units validate inputs and store a compact dictionary", {
    x <- indexed_units(c(a = 1, b = 2, c = 3), c("mg", "L", "mg"))
    expect_indexed(x, c(1, 2, 3), c("mg", "L", "mg"))
    expect_named(x, c("a", "b", "c"))
    expect_length(attr(x, "unit_dictionary"), 2)
    expect_type(attr(x, "unit_id"), "integer")
    expect_indexed(indexed_units(units::set_units(c(1, 2), h)), c(1, 2), c("h", "h"))
    expect_indexed(indexed_units(), numeric(), character())
    expect_indexed(indexed_units(1), 1, "1")
    expect_error(indexed_units(1:3, c("mg", "L")), "length")
    expect_error(indexed_units("1", "mg"), "numeric")
    expect_error(indexed_units(matrix(1:4, 2), "mg"), "vector")
    expect_error(indexed_units(1, NA_character_), "missing")
    expect_error(indexed_units(1, "not_a_real_unit"))
})

test_that("base indexing, repetition, concatenation and replacement keep units aligned", {
    x <- indexed_units(c(a = 1, b = 2), c("mg", "L"))
    expect_indexed(x[c(2, 1, 2)], c(2, 1, 2), c("L", "mg", "L"))
    expect_indexed(x["b"], 2, "L")
    expect_indexed(x[[2]], 2, "L")
    expect_indexed(x[c(1, NA, 3)], c(1, NA, NA), c("mg", NA, NA))
    expect_indexed(rep(x, each = 2), c(1, 1, 2, 2), c("mg", "mg", "L", "L"))
    expect_indexed(c(x, indexed_units(3, "s")), c(1, 2, 3), c("mg", "L", "s"))
    x["b"] <- indexed_units(4, "s")
    expect_indexed(x, c(1, 4), c("mg", "s"))
    x[4] <- indexed_units(5, "kg")
    expect_indexed(x, c(1, 4, NA, 5), c("mg", "s", NA, "kg"))
    x[[1]] <- indexed_units(6, "L")
    expect_indexed(x[1], 6, "L")
    expect_error(c(x, 1), "IndexedUnits")
})

test_that("grouped arithmetic delegates dimensional rules to units", {
    x <- indexed_units(c(1, 2, 3), c("mg", "L", "mg"))
    y <- indexed_units(c(0.001, 1000, 0.002), c("g", "mL", "g"))
    expect_indexed(x + y, c(2, 3, 5), c("mg", "L", "mg"))
    expect_indexed(x * 2, c(2, 4, 6), c("mg", "L", "mg"))
    expect_indexed(-x, c(-1, -2, -3), c("mg", "L", "mg"))
    expect_equal(x == y, c(TRUE, FALSE, FALSE))
    expect_error(x + indexed_units(1, "s"))
    expect_error(x + indexed_units(1:2, "mg"), "length")
    expect_error(sum(x), "not supported")
    expect_error(log(x), "not supported")
    expect_error(x ^ 2, "not supported")
})

test_that("base data frames preserve indexed units through row operations", {
    x <- indexed_units(c(1, 2), c("mg", "L"))
    d <- data.frame(id = 1:2, value = x)
    expect_named(d, c("id", "value"))
    expect_indexed(d[c(2, 1), ]$value, c(2, 1), c("L", "mg"))
    expect_indexed(rbind(d, d)$value, c(1, 2, 1, 2), c("mg", "L", "mg", "L"))
    expect_output(print(d), "mg")
})

test_that("empty operations and missing values retain valid metadata", {
    x <- indexed_units(c(1, NA), c("mg", NA))
    expect_indexed(x[integer()], numeric(), character())
    expect_indexed(c(indexed_units(), x), c(1, NA), c("mg", NA))
    expect_indexed(x + indexed_units(1, "g"), c(1001, NA), c("mg", NA))
    expect_indexed(x * numeric(), numeric(), character())
    expect_indexed(indexed_units(c(2, 4), "mg") / 2, c(1, 2), c("mg", "mg"))
    expect_equal(2 * indexed_units(1, "mg"), indexed_units(2, "mg"))
    expect_error(indexed_units(units::set_units(1,h), "min"), "Omit unit")
})

test_that("duplicates respect both stored values and unit labels", {
    x <- indexed_units(c(1, 1, 1), c("mg", "L", "mg"))
    expect_identical(duplicated(x), c(FALSE, FALSE, TRUE))
    expect_identical(anyDuplicated(x), 3L)
    expect_identical(anyDuplicated(x[1:2]), 0L)
    expect_indexed(unique(x), c(1, 1), c("mg", "L"))
    expect_error(sort(x), "not supported")
    expect_error(mean(x), "not supported")
})

test_that("vctrs slices, merges dictionaries, assigns and initializes missing values", {
    skip_if_not_installed("vctrs")
    a <- indexed_units(c(1, 2), c("mg", "L"))
    b <- indexed_units(c(3, 4), c("s", "mg"))
    expect_indexed(vctrs::vec_slice(a, c(2, 1)), c(2, 1), c("L", "mg"))
    expect_indexed(vctrs::vec_c(a, b), 1:4, c("mg", "L", "s", "mg"))
    expect_indexed(vctrs::vec_init(a, 2), c(NA_real_, NA_real_), c(NA_character_, NA_character_))
    expect_indexed(vctrs::vec_assign(a, 1, a[2]), c(2, 2), c("L", "L"))
})

test_that("tidyr pivots round trip numeric values and units without list columns", {
    skip_if_not_installed("tidyr")
    a <- indexed_units(c(1, 2), c("mg", "L"))
    b <- indexed_units(c(3, 4), c("s", "mg"))
    d <- data.frame(id = 1:2, a = a, b = b)
    long <- tidyr::pivot_longer(d, c(a, b))
    expect_indexed(long$value, c(1, 3, 2, 4), c("mg", "s", "L", "mg"))
    wide <- tidyr::pivot_wider(long, names_from = name, values_from = value)
    expect_indexed(wide$a, c(1, 2), c("mg", "L"))
    expect_indexed(wide$b, c(3, 4), c("s", "mg"))
    sparse <- tidyr::pivot_wider(long[-2, ], names_from = name, values_from = value)
    expect_indexed(sparse$b, c(NA, 4), c(NA, "mg"))
    expect_false(is.list(long$value))
})
